### ISSUE TITLE
Broken images in TechDocs

### ISSUE THREAD

**Issue by emmaindal** [backstage/demo#11]
As I was browsing around the demo site I could see that all images are broken within the documentation. See attached picture. 

<img width="1124" alt="Screen Shot 2020-12-15 at 5 20 42 PM" src="https://user-images.githubusercontent.com/25153114/102242070-f69a0580-3ef9-11eb-9c98-4487b4bf780f.png">

**Comment by OrkoHunter** [comment]
@backstage/maintainers 

The images are broken because they have absolute source to the host `backstage.io` which is being blocked by the Content Security Policy. I think [this](https://github.com/backstage/demo/blob/3a9ff483f4130dd96e09487f3d75267db8097d9e/app-config.yaml#L12-L13) should be updated to include `img-src https://backstage.io` (or `img-src https://*`). What do you say?


# Console errors

![Screenshot 2020-12-15 at 19 43 49](https://user-images.githubusercontent.com/8065913/102258126-e12ed680-3f0d-11eb-9c69-34a1fe0999ed.png)

Default CSP values in Backstage
https://github.com/backstage/backstage/blob/a3b2c5a68b851a4f2ba471f865c8082bfa36cba3/packages/backend-common/src/service/lib/ServiceBuilderImpl.ts#L53

**Comment by benjdlambert** [comment]
Yay more CSP issues 🙌   `img-src https://backstage.io` seems reasonable for now unless theres any other places? In which case it makes sense to just use `*` up to you folks to decide :)

**Comment by OrkoHunter** [comment]
Images loading now, wohoo

https://demo.backstage.io/docs/default/Component/backstage/features/software-catalog/

**Comment by emmaindal** [comment]
Thank you both! 🎉
