### ISSUE TITLE
Finished Getting Started, configuring Backstage - Then what?

### ISSUE THREAD

**Issue by eliassal** [backstage/demo#173]
Hi, I am new to Backstage and would like to learn how it can bue used in a devops team. I followed all instructions, it is up and running and successfully reached the end of the "Getting started......." and I have the 3 objects in home as you can notice in the snapshot.
![image](https://github.com/backstage/demo/assets/8447864/575156c0-340a-4827-af01-819bfb47509b)

So what is next? How can I use those apps/components? 
Is there any video tutorials of end-to-end usage of backstage? Up till now I am not sure I understand how to benefit from creating components, templates.....etc
Thanks for your help

**Comment by awanlin** [comment]
Hi @eliassal, terribly sorry for the sloe reply. I don't check the issue here very often. This repo really is only for hosting the Backstage Demo. 

I highly recommend joining the Backstage Discord server as it's a great place for these types of questions. You can join here: https://discord.gg/backstage-687207715902193673
